name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - name: "lint"
            command: "npm run lint"
          - name: "type-check"
            command: "npm run type-check"
          - name: "unit-test"
            command: "npm run test:unit"

    name: ${{ matrix.task.name }}

    steps:
      - name: Set up the repository
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run ${{ matrix.task.name }}
        run: ${{ matrix.task.command }}
