name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install and Build
      run: |
        npm ci
        npm run build
      env:
        VUE_APP_COSMICJS_SLUG: ${{ secrets.VUE_APP_COSMICJS_SLUG }}
        VUE_APP_COSMICJS_TOKEN: ${{ secrets.VUE_APP_COSMICJS_TOKEN }}
        VUE_APP_GITHUB_TOKEN: ${{ secrets.VUE_APP_GITHUB_TOKEN }}
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: website
        folder: dist
